### PR TITLE
fix: scrollbar visible while printing token pages and tile manifests

### PR DESCRIPTION
**Pull request by saviorsoul**
Before:
Screenshot from 2024-11-26 21-29-22
Screenshot from 2024-11-26 21-32-23

After:
Screenshot from 2024-11-26 21-27-02
Screenshot from 2024-11-26 21-33-07

### CODE REVIEW

**Comment by saviorsoul** [comment]
As this is essential part of an app, consider:

```
@media print {
  .MuiBox-root:has(.TileManifest),
  .MuiBox-root:has(.tokens) {
    overflow: visible !important;
  }
}
```

**Review by kelsin — APPROVED** [review]

**Comment by kelsin** [comment]
> As this is essential part of an app, consider:
> 
> ```
> @media print {
>   .MuiBox-root:has(.TileManifest),
>   .MuiBox-root:has(.tokens) {
>     overflow: visible !important;
>   }
> }
> ```

What is the reason to do this instead of the fix you put in?

**Comment by saviorsoul** [comment]
> > As this is essential part of an app, consider:
> > ```
> > @media print {
> >   .MuiBox-root:has(.TileManifest),
> >   .MuiBox-root:has(.tokens) {
> >     overflow: visible !important;
> >   }
> > }
> > ```
> 
> What is the reason to do this instead of the fix you put in?

It just lowers the potential risk of the change and limits it to the Tile Manifest and Tokens pages.

The printing size of tiles on Tile Manifest has changed after fixing this scroll behavior, so there are some risks with that change.

[before.pdf](https://github.com/user-attachments/files/17925872/before.pdf)
[after.pdf](https://github.com/user-attachments/files/17925873/after.pdf)

**Comment by kelsin** [comment]
Those concerns seem valid but worth just fixing since all CSS will be cleaned up soon regardless :)

**Pull request merged**
