### PR TITLE
1862 and related changes.

### PR DESCRIPTION
**Pull request by lbrande**
Solved #268. See specific commit messages for information on other fixes/improvements.

### CODE REVIEW

**Comment by kelsin** [comment]
This looks like it removes the title from the Stock Market at a global level. Can we make this an option that defaults to the current value? Otherwise it's a pretty big change from how the markets are rendered now.

**Comment by lbrande** [comment]
I guess it makes the most sense to have a key "title" that can be set to false in "par" and "market".

**Comment by lbrande** [comment]
Now you can set the key "title" to false in stock and par to hide their respective titles. If not specified "title" defaults to true. Ready for merge.

**Comment by kelsin** [comment]
thanks!

**Pull request merged**
