### PR TITLE
adding half gentles that stop halfway through the arc.  The values co…

### PR DESCRIPTION
**Pull request by th3tick**
…me from eyeballing the correct values.  There are probably more accurate answers, but

this accomplishes what I need for a game's tile set I'm working on

### CODE REVIEW

**Comment by kelsin** [comment]
Can you add some examples to the atoms page too, and then we'll pull that in.

**Comment by kelsin** [comment]
ok I think I want to add more track options later. The idea would be to allow for a field that take either a number or an array of two numbers. It would then draw a normal straight/gentle/sharp but stop it at the percent of the number, or draw it from the start to the end. So for instance a current "mid" track would be `[0.25,0.5]` and a half gentle would be `0.5` of a normal gentle or `[0.5,1]` for the second half of one. That would allow people to do... almost anything they want and we could get rid of ALL of the "stop" / "stub" / "mid" etc track. I will work on this later.

**Comment by th3tick** [comment]
OK, but when you do, please preserve the existing ones.  I have no problem fixing up the new ones in the game I used them in, but keep the other ones so none of the put-back games are broken.  A translation layer or something would be helpful.  Also, something to indicate that a file uses deprecated features would be good - even for the tile files.

**Comment by kelsin** [comment]
Games repo fully updated with new options. Schemas updated to not validate with old track styles. Script in the games repo available that will update a game file with the common used ones: https://github.com/18xx-maker/games/blob/master/bin/0004-fix-trackTypes.js

If you need help running it let me know. All old track types including your new ones are there still, just won't validate.

**Pull request closed without merging**
